title: Tufa Labs
description: >-
  Public website for Tufa Labs, a small independent research group working on
  fundamental AI research.
url: "https://tufalabs.ai"
baseurl: ""
timezone: "Europe/Zurich"
lang: "en-US"
destination: ../docs
markdown: kramdown
include:
  - .nojekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  path: research/feed.xml

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      nav_id: research
  - scope:
      path: ""
    values:
      layout: page
